### ISSUE TITLE
League of Legends

### ISSUE THREAD

**Issue by mandruis** [iXit/xf86-video-ati#1]
League.log 45 KB
https://mega.co.nz/#!RI0DmZyL!FKzurVii6gkxjmF11PZMWJFsG7pDJHW5LNOvzT6FN5I

Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
fixme:thread:start_thread Started native thread 000000dc
fixme:win:EnumDisplayDevicesW ((null),0,0x33f284,0x00000000), stub!
fixme:thread:start_thread Started native thread 0000006c
fixme:thread:start_thread Started native thread 00000067
fixme:thread:start_thread Started native thread 000000de
fixme:thread:start_thread Started native thread 000000d1
fixme:thread:start_thread Started native thread 000000d2
fixme:thread:start_thread Started native thread 0000006d
fixme:thread:start_thread Started native thread 000000d9
fixme:thread:start_thread Started native thread 00000070
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33f284,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x33f284,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x33f284,0x00000000), stub!
fixme:d3d9:d3dadapter9_new 
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
fixme:win:EnumDisplayDevicesW ((null),0,0x9a2d294,0x00000000), stub!
fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
fixme:imm:ImmReleaseContext (0x100be, 0x4c3e658): stub
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33ec44,0x00000000), stub!
radeon: Failed to allocate a buffer:
radeon:    size      : 4352 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    flags     : 4
radeon: Failed to allocate a buffer:
radeon:    size      : 4352 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    flags     : 4
fixme:devenum:DEVENUM_ICreateDevEnum_CreateClassEnumerator Category {33d9a761-90c8-11d0-bd43-00a0c911ce86} not found
fixme:devenum:DEVENUM_ICreateDevEnum_CreateClassEnumerator Category {cc7bfb41-f175-11d1-a392-00e0291f3959} not found
fixme:devenum:DEVENUM_ICreateDevEnum_CreateClassEnumerator Category {cc7bfb46-f175-11d1-a392-00e0291f3959} not found
fixme:wbemprox:client_security_SetBlanket 0x7c94d610, 0xf3a99f0, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0x7c94d610
fixme:win:EnumDisplayDevicesW ((null),0,0x9a2e004,0x00000000), stub!
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub

**Comment by okias** [comment]
If it's still valid problem, please move bug to Mesa-3D component, DDX should not interfere with this problem.
