### ISSUE TITLE
Enough of that repo

### ISSUE THREAD

**Issue by axeldavy** [iXit/xf86-video-ati#2]
Please David, can you do something so that people don't use the repo anymore ?

The plan is to push a commit that erase all files and change README to say to use the official master repo.

We have countless of people using that repo whereas they should realy use the official one.
I don't have any right on that repo.
Idea is to not lose the history thuw why a commit to erase things.

**Comment by okias** [comment]
I didn't found commit where is DRI3 enabled in default -ati driver by default. Maybe I'll do some rebase on top of actual code tomorrow (if I make it) ?

**Comment by axeldavy** [comment]
Make a copy of the master branch to another branch then.
Idea is to have history we were first :-)

**Comment by okias** [comment]
Done & synced. Thank you :)
